import type { CSSProperties } from "react";

/**
 * Responsive <picture> for the site photos. Emits AVIF → WebP <source>s (with
 * width-based srcset + sizes) and falls back to the committed JPEG master as the
 * <img src>. Variants live at /img/<name>-<w>.{avif,webp} and are generated by
 * `scripts/gen-images.mjs` (committed) — the `widths` passed here MUST match a ladder
 * that script produces, or the largest srcset entries 404 (the <img> JPEG still shows).
 *
 * Pure render-time function (no hooks/window) so server prerender and client hydration
 * produce identical markup. CLS-safe: pass width/height for uncropped images (hero,
 * story) whose intrinsic ratio matches the display; rely on CSS aspect-ratio (no
 * width/height) for the cropped card/feature images so the box stays locked.
 */
const stem = (src: string) => src.replace(/\.jpe?g$/i, "");
const srcset = (base: string, ext: string, widths: number[]) =>
  widths.map((w) => `${base}-${w}.${ext} ${w}w`).join(", ");

export function Picture({
  src,
  alt,
  widths,
  sizes,
  width,
  height,
  eager = false,
  className,
  style,
}: {
  /** Committed JPEG master, e.g. "/img/product-serum.jpeg". */
  src: string;
  alt: string;
  widths: number[];
  sizes: string;
  width?: number;
  height?: number;
  /** Hero/LCP: render eagerly (priority comes from the responsive preload in index.html). */
  eager?: boolean;
  className?: string;
  style?: CSSProperties;
}) {
  const base = stem(src);
  return (
    <picture>
      <source type="image/avif" srcSet={srcset(base, "avif", widths)} sizes={sizes} />
      <source type="image/webp" srcSet={srcset(base, "webp", widths)} sizes={sizes} />
      <img
        src={src}
        alt={alt}
        width={width}
        height={height}
        loading={eager ? undefined : "lazy"}
        decoding="async"
        className={className}
        style={style}
      />
    </picture>
  );
}
